# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title R interface to complex gamma function.
#' @param inRvec complex vector or 2d matrix of complex numbers
#' @details The `Rcomplex` data structure definition has changed
#' recently in `R_ext/Complex.h`.
#' @return Returns a vector or matrix of complex values.
cgammacpp <- function(inRvec) {
    .Call(`_Mypack_cgammacpp`, inRvec)
}

#' @title Return C++ toolchain used to build package \code{Mypack}
#' @details
#' The Windows toolchain (MSVC) shows version info MMNNBBBBB, where
#' MM=Major, NN=Minor, and BBBBB=Build.
cpptoolchain <- function() {
    .Call(`_Mypack_cpptoolchain`)
}

