    const char *R_VARS[] = {
        "R_ARCH", "",
        "R_BROWSER", "/usr/bin/xdg-open",
        "R_BZIPCMD", "/usr/bin/bzip2",
        "R_DOC_DIR", "/usr/local/lib/R/4.5.1/lib/R/doc",
        "R_GZIPCMD", "/usr/bin/gzip",
        "R_HOME", "/usr/local/lib/R/4.5.1/lib/R",
        "R_INCLUDE_DIR", "/usr/local/lib/R/4.5.1/lib/R/include",
        "R_LIBS_SITE", "/usr/local/lib/R/4.5.1/lib/R/site-library",
        "R_LIBS_USER", "/home/dsamperi/R/x86_64-pc-linux-gnu-library/4.5",
        "R_PAPERSIZE", "letter",
        "R_PDFVIEWER", "/usr/bin/xdg-open",
        "R_PLATFORM", "x86_64-pc-linux-gnu",
        "R_PRINTCMD", "lpr",
        "R_RD4PDF", "times,inconsolata,hyper",
        "R_SHARE_DIR", "/usr/local/lib/R/4.5.1/lib/R/share",
        "R_STRIP_SHARED_LIB", "strip --strip-unneeded",
        "R_STRIP_STATIC_LIB", "strip --strip-debug",
        "R_TEXI2DVICMD", "/usr/bin/texi2dvi",
        "R_UNZIPCMD", "/usr/bin/unzip",
        "R_ZIPCMD", "/usr/bin/zip",
        NULL
    };
